version = 0.1

[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::192987814957:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-XBSbp771iTPF"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::192987814957:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-nDEgHgObAPnh"
cloudformation_execution_role = "arn:aws:iam::192987814957:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-uKQk8bG7Lb7u"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-4gpoqbot8wtf"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::192987814957:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-6KUsitMAajuV"
cloudformation_execution_role = "arn:aws:iam::192987814957:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-U66B7ca1N6wQ"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-8mvyxee9weva"
image_repository = ""
region = "us-east-2"
